import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import Link from "next/link";
import { Layout, Menu } from "antd";
import { Content, Footer, Header } from "antd/es/layout/layout";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const items = [
  { key: 0, label: <Link href={'/'}>Home</Link> },
  { key: 1, label: <Link href={'/posts'}>Posts</Link> },
  { key: 2, label: <Link href={'/albums'}>Albums</Link> },
  { key: 3, label: <Link href={'/todos'}>Todos</Link> }
]

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <AntdRegistry>
          <Layout className="layout">
            <Header className="header">
              <Menu 
              theme="dark"
              mode="horizontal"
              defaultSelectedKeys={['0']}
              items={items}
              style={{flex: 1, minWidth: 0}}
              />
            </Header>
            <Content className="content">{children}</Content>
            <Footer className="footer">Footer</Footer>
          </Layout>
        </AntdRegistry>
      </body>
    </html>
  );
}
